exp_name: OmniDiTXL_restore_diffdb_sigma-2
seed: 18
checkpoint_path: giannisdaras/ambient-o
output_dir: ./outputs/restored_images/ambient-o/restore_diffdb
sigma_tn: 2.0
num_batches: -1
num_restorations: 1
model:
  _target_: micro_diffusion.models.model_ambient.create_ambient_diffusion
  vae_name: stabilityai/stable-diffusion-xl-base-1.0
  text_encoder_name: openclip:hf-hub:apple/DFN5B-CLIP-ViT-H-14-378
  dit_arch: MicroDiT_XL_2
  precomputed_latents: true
  in_channels: 4
  pos_interp_scale: 2.0
  dtype: 'float32'
  latent_res: 64
  p_mean: 0
  p_std: 0.6
  train_mask_ratio: 0.0
dataset:
  image_size: 512 # 8 * latent_res
  train_batch_size: 2048
  eval_batch_size: 512
  cap_drop_prob: 0.1
  eval:
    _target_: micro_diffusion.datasets.latents_loader_for_restore.build_streaming_latents_dataloader
    datadir: ./datadir/coco/mds_latents_sdxl1_dfnclipH14
    drop_last: false
    shuffle: true
    prefetch_factor: 2
    num_workers: 2
    persistent_workers: true
    pin_memory: true
guidance_scale: 5
sampling_steps: 30
save_dtype: float16
